### ISSUE TITLE
Cosicas tontas

### ISSUE THREAD

**Issue by fgr1986** [fgr1986/simple_server_client#5]
Para @dperezde 
1) en cliente, pasar bucles a modern:
`for (std::vector<int>::size_type i = 0 ; i < r_ids.size(); ++i ) {`
2) A una lambda:
`
auto cap = id.capacity();
	for (size_t i = 1 ; i <= cap; ++i) {
		id.emplace_back(i);
}`
3) Seguir el estilo del resto del proyecto: 
Para identificar atributos de clase 

  ```
int server_size;
  std::vector<int> r_ids;
  std::vector<std::string> names {"Alice", "Bob", "Eve", "Mallory"};....
```

debe ser (revisa todo please)

```
  int server_size_;
  std::vector<int> r_ids_;
  std::vector<std::string> names_ {"Alice", "Bob", "Eve", "Mallory"};....
```

**Comment by dperezde** [comment]
> Primera vez que lo veo
:man_facepalming: 
Se me había olvidado la existencia de los range for loops

**Comment by dperezde** [comment]
@fgr1986 Si cierras el pull request creo que no se actualiza tu repo con los cambios que yo subo y tampoco te llegarán los emails con los cambios.

**Comment by fgr1986** [comment]
Queda el tema de nombres en atributos de clase,acondicionando el estilo.
